name: Compile and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build code base
    runs-on: "ubuntu-22.04"
    container:
      image: niemiti/ofdevcuda:latest
      options: --user root
    steps:
    - name: Checkout gpuFoam
      uses: actions/checkout@v3
    - name: Build gpuFoam
      run: export GPUFOAM_BACKEND_NVIDIA=1 && source /opt/OpenFOAM/OpenFOAM-dev/etc/bashrc && ./Allwmake
      shell: bash
    - name: Run unittests on GPU
      run: source /opt/OpenFOAM/OpenFOAM-dev/etc/bashrc && Test-gpuChemistry [CPU]
      shell: bash
