name: Compile and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:
    name: Build code base
    runs-on: "ubuntu-22.04"
    container:
      image: hamsteri15/of_dev_build:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
      options: --user root
    steps:
    - name: Checkout gpuFoam
      uses: actions/checkout@v3   
    - name: Build gpuFoam      
      run: source /home/foam/OpenFOAM-dev/etc/bashrc && ./Allwmake
      shell: bash
    - name: Run unittests
      run: testGpuChemistry
